### ISSUE TITLE
Warning: Tolk output requested but no active screen reader for trigger

### ISSUE THREAD

**Issue by Gchorba** [FedUni/SoniFight#1]
Trying out SoniFight as a way for a hard of sight friend to play games with us. Unfortunately we keep running into the following warnings and now sound playing. 

Warning: Tolk output requested but no active screen reader for trigger with ID: 204
Found match for trigger: 205 with value: 5
Warning: Tolk output requested but no active screen reader for trigger with ID: 205
Found match for trigger: 206 with value: 6
Warning: Tolk output requested but no active screen reader for trigger with ID: 206
Found match for trigger: 207 with value: 7
Warning: Tolk output requested but no active screen reader for trigger with ID: 207
Found match for trigger: 208 with value: 8

**Comment by ghost** [comment]
Hi,

I assume you're using the BlazBlue Continuum Shift Extend config... So, the issue is that triggers 205 to 208 *DON'T* cause your screen reader to say anything? Or that they *KEEP* triggering (when they probably shouldn't) and saying things like "Resolution Setting" [205], "Screen Mode" [206], "Restore Defaults" [207] and "Return to Options Menu" [208]?

If the triggers KEEP triggering when they shouldn't you can just go to them in the Edit Tab and uncheck the **Active** checkbox for each trigger and then save the config.

I've just tried the config out again to see if I could spot any issues, but it's all working as planned for me - no major 'spamming' of inappropriate triggers (although the occasional inappropriate trigger occurs as the game sets itself up), and all triggers working as designed.

All the BlazBlue config triggers use the Tolk screen reader abstraction library to cause your screen reader to say various things based on menu options / the state of the game etc. I've tested SoniFight with the NVDA screen reader, although many different screen readers are supported. Here's the tolk screen reader compatibility list:

[https://github.com/dkager/tolk#supported-screen-readers](https://github.com/dkager/tolk#supported-screen-readers)

I thought that list of screen readers was in the user guide, but aparently not - so I'll add it when I've finished the upcoming SoniFight v1.1.5 which should be in less that a week.

Also, when you start SoniFight you should see whether it's got some ability to make sound or not as you should see output such as:

> irrKlang sound library version 1.5.0
Loaded plugin: ikpflac_32.dll
Loaded plugin: ikmp3_32.dll
Using DirectSound8 driver

If that's missing, or you're not using a supported screen reader perhaps that's the problem?

If that doesn't help, get back to me with some more details of what's going on and I'll see what I can do.

**Comment by Gchorba** [comment]
Resolved the issue. The screen reader was being blocked due to windows security. Switching to NVDA fixed it.
